### ISSUE TITLE
support desired_capabilities: acceptSslCerts=True

### ISSUE THREAD

**Issue by bmannix** [detro/ghostdriver#233]
PhantomJS itself supports ignoring/accepting SSL certs based on a flag when starting the browser, however GhostDriver does not support the ability to accept all SSL certs.  This functionality is supported by the WebDriver spec via desired_capabilities.

Here is a python snippet demonstrating the inability to set `acceptSslCerts=True`

```python
from selenium import webdriver

dcaps = {'acceptSslCerts':True}
browser = webdriver.PhantomJS(desired_capabilities=dcaps)

browser.get('https://<some url with an invalid cert>')
```

At this point the page is not loaded

```
In [5]: browser.page_source
Out[5]: u'<html><head></head><body></body></html>'

In [7]: browser.capabilities['acceptSslCerts']
Out[7]: False
```

Being that PhantomJS and WebDriver support the behavior, GhostDriver should include it as well.

**Comment by jerrywiltse** [comment]
I'm a novice here, but even when providing the SSL parameters via CLI in eclipse/java I can't get ""acceptSslCerts" to set to true.  I've tried about 4 samples I've found in forums here and none seem to work for me. 

My console log here shows that "--ignore-ssl-errors=yes" is being detected as a CLI parameter, also tried "true" instead of yes. Then, in the negotiated capabilities, it shows:

"acceptSslCerts":false

Any ideas? 


Here's the code: 
```
File file = new File(libPath+"phantomjs.exe");
System.setProperty("phantomjs.binary.path", file.getAbsolutePath());
DesiredCapabilities capabilities = DesiredCapabilities.phantomjs()
capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, ["--web-security=no", "--ignore-ssl-errors=true"] as String[]);
capabilities.setCapability("takesScreenshot", false);
driver = new PhantomJSDriver(capabilities);
```

Here's the Log: 
```
Jul 19, 2015 6:22:15 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: C:\workspace\phantomproject\lib\phantomjs.exe
Jul 19, 2015 6:22:15 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 12138
Jul 19, 2015 6:22:15 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--web-security=no, --ignore-ssl-errors=true, --webdriver=12138, --webdriver-logfile=C:\workspace\phantomproject\phantomjsdriver.log]
Jul 19, 2015 6:22:15 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
[INFO  - 2015-07-19T22:22:18.156Z] GhostDriver - Main - running on port 12138
[INFO  - 2015-07-19T22:22:18.583Z] Session [9deb29b0-2e64-11e5-b139-81bc3c7ef56b] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 Safari/538.1","webSecurityEnabled":false}
[INFO  - 2015-07-19T22:22:18.584Z] Session [9deb29b0-2e64-11e5-b139-81bc3c7ef56b] - page.customHeaders:  - {}
[INFO  - 2015-07-19T22:22:18.584Z] Session [9deb29b0-2e64-11e5-b139-81bc3c7ef56b] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.0.0","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"windows-unknown-32bit","javascriptEnabled":true,"takesScreenshot":false,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-07-19T22:22:18.584Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 9deb29b0-2e64-11e5-b139-81bc3c7ef56b
```

**Comment by jerrywiltse** [comment]
Did I post this in the correct place? If not, should I post this under another area?

**Comment by chrisclark** [comment]
@sinhanurag at the risk of being a full year late to the party, here's how we (*finally*) got this working in JS (coffeescript):

```
      webdriver = require 'selenium-webdriver'
      capabilities = webdriver.Capabilities.phantomjs()
      capabilities.set webdriver.Capability.ACCEPT_SSL_CERTS, true
      capabilities.set webdriver.Capability.SECURE_SSL, false
      capabilities.set "phantomjs.cli.args", ["--web-security=no", "--ssl-protocol=any", "--ignore-ssl-errors=yes"]
      driver = new webdriver
        .Builder()
        .withCapabilities(capabilities)
        .setControlFlow(new webdriver.promise.ControlFlow())
        .build();
```

**Comment by detro** [comment]
I think #388 is a step in the right direction for this

**Comment by jerrywiltse** [comment]
Based on a number of posts surrounding SSL, a number of people say they got this working like chrisclark. I don't know if I'm the only person still having an issue, so I'm not even sure #388 addresses the issue I'm having. Can anyone else reproduce the symptom I posted in Java?

**Comment by ashdsouza** [comment]
I have the same issue as @jerrywiltse in Java. Trying to set acceptSslCerts=true using capabilities, however "acceptSslCerts":false is always the case when pahntomjs runs on my linux machine.

`capabilities.setJavascriptEnabled(true);
		capabilities.setCapability("takesScreenshot", false);
		capabilities.setCapability("acceptSslCerts", true);
		capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, new String[] {"--web-security=false", "--ssl-protocol=any", "--ignore-ssl-errors=true"});
		capabilities.setCapability("phantomjs.binary.path", this.phantomjsPath);`

This results in [https://github.com/ariya/phantomjs/issues/11526](url) too.

**Comment by adamwardecki** [comment]
I'm having the same issue as @jerrywiltse and @ashdsouza 
For some reason `acceptSslCerts` set to true is ignored.

Other browsers (Chrome, FF) work fine and the flag is being set to true.
Here are the session logs:
```
INFO Request: POST /wd/hub/session
 - data:  {"desiredCapabilities":{"browserName":"phantomjs","javascriptEnabled":true,"acceptSslCerts":true,"platform":"ANY","phantomjs.binary.path":"./bin/phantomjs","phantomjs.cli.args":["--web-security=false","--ignore-ssl-errors=true"],"name":"Instances / Test Administrators"}}
 - headers:  {"Content-Type":"application/json; charset=utf-8","Content-Length":271}
INFO Response 200 POST /wd/hub/session{ status: 0,
  sessionId: '3606320f-5e0c-4f23-b70b-2216a4f1f71c',
  value:
   { platform: 'MAC',
     acceptSslCerts: false,
     javascriptEnabled: true,
     browserName: 'phantomjs',
     rotatable: false,
     driverVersion: '1.1.0',
     locationContextEnabled: false,
     'webdriver.remote.sessionid': '3606320f-5e0c-4f23-b70b-2216a4f1f71c',
     version: '1.9.7',
     cssSelectorsEnabled: true,
     databaseEnabled: false,
     handlesAlerts: false,
     browserConnectionEnabled: false,
     webStorageEnabled: false,
     nativeEvents: true,
     proxy: { proxyType: 'direct' },
     applicationCacheEnabled: false,
     driverName: 'ghostdriver',
     takesScreenshot: true },
  state: null,
  class: 'org.openqa.selenium.remote.Response',
  hCode: 1567133135 }
INFO Got sessionId from selenium 3606320f-5e0c-4f23-b70b-2216a4f1f71c
```

**Comment by incloser** [comment]
In my case the problem was in Antivirus Setting(Safe Browsing). The answer was found at mozilla's support site. Maybe it will help someone.

**Comment by atalis** [comment]
Three and a half years later, and the issue is still there for me.  I scoured the net for possible solutions and tried various combinations of parameters, but still no luck.

Invoking in CLI:
`phantomjs --webdriver=localhost:4444 --web-security=false --ignore-ssl-errors=true --ssl-protocol=any`

Attempted variations of setting webdriver's ACCEPT_SSL_CERTS to true in protractor.config.js file, based on the posts here and phantomjs source code:

`capabilities: 
{
    browserName: 'phantomjs',
    'phantomjs.ghostdriver.cli.args': [' --ignore-ssl-errors=true ', ' --web-security=false'],
    'phantomjs.ghostdriver.Capability.ACCEPT_SSL_CERTS': true,
    'webdriver.Capability.ACCEPT_SSL_CERTS': true,
    'webdriver.WebDriver.Capability.ACCEPT_SSL_CERTS': true
  }`

None of this is working.  If anyone had a breakthrough, please share it.

**Comment by rbarbaresco** [comment]
As @atalis said, "Three and a half years later, and the issue is still there for me.". All his alternatives I have already tried and there's just no effect at all.
Only thing that actually worked was passing the "service_args" in the PhantomJS initialization, which is no option in my project:

```
webdriver.PhantomJS(executable_path='phantomjs', desired_capabilities=dict(DesiredCapabilities.PHANTOMJS), service_args=['--web-security=no', '--ssl-protocol=any', '--ignore-ssl-errors=yes'])
```

If anyone would have a solution, please share it.
