### ISSUE TITLE
How to set the log level using PhantomJSDriver?

### ISSUE THREAD

**Issue by Honigbaum** [detro/ghostdriver#338]
Hi, 

I've installed the PhantomJS executables and using PhantomJSDriver from my Scala source. Every time I use the driver I get the following log messages: 

```
[error] PhantomJS is launching GhostDriver...
[error] [INFO  - 2014-05-02T11:26:19.827Z] GhostDriver - Main - running on port 19405
[error] [INFO  - 2014-05-02T11:26:20.024Z] Session [95657c30-d1ec-11e3-aad6-b9181c8b3f22] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; PPC Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.7 Safari/534.34","webSecurityEnabled":true}
[error] [INFO  - 2014-05-02T11:26:20.024Z] Session [95657c30-d1ec-11e3-aad6-b9181c8b3f22] - page.customHeaders:  - {}
[error] [INFO  - 2014-05-02T11:26:20.024Z] Session [95657c30-d1ec-11e3-aad6-b9181c8b3f22] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.7","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"mac-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[error] [INFO  - 2014-05-02T11:26:20.024Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 95657c30-d1ec-11e3-aad6-b9181c8b3f22
[error] [ERROR - 2014-05-02T11:26:21.699Z] Session [95657c30-d1ec-11e3-aad6-b9181c8b3f22] - page.onError - msg: ReferenceError: Can't find variable: define
[error] [ERROR - 2014-05-02T11:26:21.699Z] Session [95657c30-d1ec-11e3-aad6-b9181c8b3f22] - page.onError - stack:
[error]   (anonymous function) (http://localhost:19001/product/assets/scripts/ev.js:7)
[error]   (anonymous function) (http://localhost:19001/product/assets/scripts/ev.js:11)
[error] [INFO  - 2014-05-02T11:26:21.929Z] ShutdownReqHand - _handle - About to shutdown
```

I tried several ways to disable these messages: 

First: 
```
val driver: PhantomJSDriver = new PhantomJSDriver(capabilities)
driver.setLogLevel(Level.OFF)
```

Didn't work

Second: 
```
val build: PhantomJSDriverService = new PhantomJSDriverService.Builder().withLogFile(new File(null)).build()
val driver: PhantomJSDriver = new PhantomJSDriver(build, capabilities)
```

Didn't work

Third:

```
capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_GHOSTDRIVER_CLI_ARGS, "--logLevel=NONE")
val driver: PhantomJSDriver = new PhantomJSDriver(capabilities)
```

Didn't work, but here I found a comment in PhantomJSDriverService.java, that this option only has effect if the path of the GhostDriver executable is set too. But where do I find these executable, it's integrated in PhantomJS?!

Is there ANY way to disable these logs?!

Thank you

**Comment by hoffm263** [comment]
Thought I would throw this out there since I had a ton of trouble getting it to work with the Java API + PhantomDriver. I finally got it working with the following (I included the a few other properties that are not necessary just to show how they are set as well). 

//there is a special place in hell for people who post code without dependencies/imports 
//you need selenium-java-2.45.0.jar and phantomjsdriver-1.2.1.jar
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriverService;
import org.openqa.selenium.remote.DesiredCapabilities;
.......
.......

DesiredCapabilities capabilities = DesiredCapabilities.phantomjs();
	capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_PAGE_SETTINGS_PREFIX + "userAgent", "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36");
			capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_PAGE_SETTINGS_PREFIX + "loadImages", true);
			capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_PAGE_SETTINGS_PREFIX + "javascriptEnabled", true);
			capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_PAGE_SETTINGS_PREFIX + "resourceTimeout", 60000);
			capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, new  String[] {"--webdriver-loglevel=NONE"});//NONE,ERROR
			WebDriver driver = new PhantomJSDriver(capabilities);

**Comment by testinfected** [comment]
To silence the PhantomJSDriverService, you can simply do:

`Logger.getLogger(PhantomJSDriverService.class.getName()).setLevel(Level.OFF)`

**Comment by detro** [comment]
Thanks @testinfected

**Comment by harishvc** [comment]
import os
driver = webdriver.PhantomJS(service_log_path=os.path.devnull)

**Comment by gattaccio8** [comment]
capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_GHOSTDRIVER_CLI_ARGS, "--logLevel=NONE")
val driver: PhantomJSDriver = new PhantomJSDriver(capabilities)

worked for me

**Comment by igniteram** [comment]
how can we disable this in nodejs webdriver with phantomjs-prebuilt api bindings?? can anyone help me on this? there is no such info anywhere.

**Comment by johnnyqian** [comment]
While using C#, below code is working fine for me:

```csharp
var driverService = PhantomJSDriverService.CreateDefaultService(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location));
driverService.SuppressInitialDiagnosticInformation = true;
driverService.AddArgument("--webdriver-loglevel=NONE");
driver = new PhantomJSDriver(driverService);
```
