### ISSUE TITLE
Allow GhostDriver to bind to a specific IP

### ISSUE THREAD

**Issue by danidemi** [detro/ghostdriver#390]
I'm trying to run PhantomJS/GhostDriver on OpenShift, where an application is authorized to bind just to a particular IP that is stored, in my setup, in the OPENSHIFT_DIY_IP env variable.

When I run PhantomJS I get this error:

    $ ./phantomjs --webdriver=${OPENSHIFT_DIY_IP}:29234
    PhantomJS is launching GhostDriver...
    [ERROR - 2014-09-09T16:10:18.630Z] GhostDriver - main.fail - {"message":"Could not start Ghost   Driver","line":82,"sourceId":139814638960128,"sourceURL":":/ghostdriver/main.js","stack":"Error:   Could not start Ghost Driver\n    at :/ghostdriver/main.js:82","stackArray":[{"sourceURL":":/ghostdriver/main.js","line":82}]}

As far as I understood, it is not yet possible to specify Ghostdriver the IP it should bind to, but it would be great if that would be possible.

I already opened the [issue](https://github.com/ariya/phantomjs/issues/12553) in PhantomJS but it has been closed, and I was requested to reopen it for Ghostfriver.

**Comment by zhushanhu** [comment]
I think somebody has a resolution of this issue, you can check this webste: https://paolobernardi.wordpress.com/2015/02/25/phantomjs-with-ghostdriver-on-openshift/

and you'd better use an external ghostdriver as it doesn't need to rebuild phantomjs
