### ISSUE TITLE
Converting HTML to PDF

### ISSUE THREAD

**Issue by 1dson** [detro/ghostdriver#429]
Is it possible to convert an HTML to PDF using Ghost driver similar to this 

phantomjs rasterize.js 'http://en.wikipedia.org/w/index.php?title=Jakarta&printable=yes' jakarta.pdf

**Comment by seisler** [comment]
I'm stuck in the same point. If PhantomJS does, GhostDriver may do it too. Some news?

**Comment by 1dson** [comment]
I ended up using another library to convert my HTML into PDF

http://selectpdf.com/community-edition/

// instantiate the html to pdf converter
HtmlToPdf converter = new HtmlToPdf();

// convert the url to pdf
PdfDocument doc = converter.ConvertUrl(url);

// save pdf document
doc.Save(file);

// close pdf document
doc.Close();

**Comment by seisler** [comment]
Thanks a lot @1dson ! :)
