### ISSUE TITLE
Is ghostdriver (on github) doomed?

### ISSUE THREAD

**Issue by luksch** [detro/ghostdriver#433]
Sorry for the pathetic headline, but I really wonder if this project is still under development here on github. I am a user of this fantastic webdriver implementation for quite some time now. It is very valuable for me, but since Selenium  2.45 is now already available and it ships with Ghostdriver Implementation-Version: 1.2.1 I am utterly confused about the status of the project. Can someone enlighten me?

Best regards,
Lukas

**Comment by christopherbalz** [comment]
Is there a selenium-standalone node package that has the support you mention above? The version numbers for the standalone end at 2.44 before going to 3.x and 4.x .  With 4.x and the latest webdriver and jasmine-node packages, phantom still doesn't work - 

```
### Execution Started ### Running Test which does foo when bar is clicked.
{ [RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: org/openqa/selenium/browserlaunchers/Proxies

     Callstack:
     -> init()
```

**Comment by chrylis** [comment]
Take a look at [`com.codeborne:phantomjsdriver`](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22phantomjsdriver%22).

**Comment by nomadcanuck** [comment]
see https://code.google.com/p/selenium/issues/detail?id=8088

**Comment by asolntsev** [comment]
@luksch @chrylis @nomadcanuck

Since Ivan de Marino cannot support the project anymore, we created [a fork](https://github.com/codeborne/ghostdriver) and released a new version of phantomjsdriver that is compatible with
* latest PhantomJS 2.2.1, and 
* latest selenium 2.53.0

You can find it in the maven central repository:
```xml
<dependency>
  <groupId>com.codeborne</groupId>
  <artifactId>phantomjsdriver</artifactId>
  <version>1.3.0</version>
</dependency>
```

**Comment by jesg** [comment]
ghostdriver is under active development.
