### ISSUE TITLE
Element is not currently visible and may not be manipulated bug fix

### ISSUE THREAD

**Issue by stevenliuit** [detro/ghostdriver#443]
In submitting the form, appearance (Element is not currently visible and may not be manipulated) error. Found to be caused by the page size. Would like to add the page size of the code in session.js years, as the initialization parameters.

page = _decorateNewWindow(require("webpage").create());
page.viewportSize = {width: 1024,height: 768};

**Comment by jesg** [comment]
[1366x768](https://github.com/detro/ghostdriver/blob/master/src/session.js#L582) is the new default `viewportSize`.
