### ISSUE TITLE
Is it possible to set screen resolution with ghostdriver?

### ISSUE THREAD

**Issue by dhoer** [detro/ghostdriver#446]
I'm trying to set the screen resolution but have not been successful.  Can you provide an example of how to do this?  Here is what I thought should work, but it returns 1024x768. I also tried viewportSize with no success.

``` 
  before(:all) do
    @selenium = Selenium::WebDriver.for(:remote, url: 'http://localhost:8911')
    target_size = Selenium::WebDriver::Dimension.new(1280, 1024)
    @selenium.manage.window.size = target_size
  end

  after(:all) do
    @selenium.quit
  end

  it 'Should return display resolution of 1280x1024' do
    @selenium.get 'http://www.whatismyscreenresolution.com/'
    element = @selenium.find_element(:id, 'resolutionNumber')
    expect(element.text).to eq('1280 x 1024')
  end
```

**Comment by wongterrencew** [comment]
That website, http://www.whatismyscreenresolution.com/, is not grabbing the window size correctly for some reason. Your code is in fact correct, if you take a screenshot you'll see that the resolution of the screenshot matches the correct window dimensions.

```
require 'selenium-webdriver'
require 'rspec/expectations'
include RSpec::Matchers

def setup
  @driver = Selenium::WebDriver.for :remote, url: 'http://localhost:8001'
  target_size = Selenium::WebDriver::Dimension.new(1280, 1024)
  @driver.manage.window.size = target_size
end

def teardown
  @driver.quit
end

def run
  setup
  yield
  teardown
end

run do
  @driver.get 'http://www.whatismyscreenresolution.com/'
  @driver.save_screenshot('screenshot.png')
  file_info = `file screenshot.png`.chomp
  expect(file_info).to eq('screenshot.png: PNG image data, 1280 x 1024, 8-bit/color RGBA, non-interlaced')
end
```

**Comment by dhoer** [comment]
Thanks for the feedback, but that didn't work (Ubuntu 14.04):

```
     expected: "screenshot.png: PNG image data, 1280 x 1024, 8-bit/color RGBA, non-interlaced"
            got: "screenshot.png: PNG image data, 1280 x 58875, 8-bit/color RGBA, non-interlaced"
```

**Comment by dhoer** [comment]
That was the result if I used http://www.screenresolution.org/ instead of http://www.whatismyscreenresolution.com/.  Using http://google.com work properly as well.  Thanks again for the help.

**Comment by dhoer** [comment]
FYI, that code is used here: https://github.com/dhoer/chef-selenium/blob/master/test/integration/selenium_test/rspec/phantomjs_spec.rb
