### ISSUE TITLE
Get to a non-existent url, use getPageSource it returns the source of the previous url source.

### ISSUE THREAD

**Issue by Accagain2014** [detro/ghostdriver#460]
When I use driver.get("dfldjkf") (a non-existent url), I want to get the empty source, but it returns the source of the previous one. 

How can I solve the problem.

I want to get a lot of urls's souce, so I use driver.get(oneurl),and get the source driver.getPageSource(),and then I use driver.get(anotherurl, and get the source driver.getPageSource().

How can I close a window, just the window, not the phantomjs.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://loadwallet.net/deer.php?h>

 

klaus@hebsgaard.dk

**Comment by jesg** [comment]
@Accagain2014 you should use `driver.get("about:blank")` if you want an empty page.

webdriver provides access to window handles.  you should be able to switch windows and close them.
