### ISSUE TITLE
[w3c] update selenium timeouts to w3c standard

### ISSUE THREAD

**Issue by jesg** [detro/ghostdriver#488]
the current default timeouts in ghostdriver are:

script: 2^31 -1 milliseconds
page timeout: 2^31-1 milliseconds
implicit: 200 milliseconds

per [w3c webdriver spec](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-session-script-timeout) it should be:

script: 30,000 milliseconds
page timeout: 300,000 milliseconds
implicit: 0 milliseconds

**Comment by asevans48** [comment]
Thanks. I will track this as well. Perhaps I could try a pull request as well but am really, really busy.  The overall feedback and improvements over time have been great. In the meantime, perhaps the ticket remains open?

**Comment by asevans48** [comment]
It is still a major problem.

[INFO  - 2016-10-17T16:40:52.635Z] Session [77b65540-9488-11e6-8b50-6587ab547a16] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":false}
[INFO  - 2016-10-17T16:40:52.635Z] Session [77b65540-9488-11e6-8b50-6587ab547a16] - page.customHeaders:  - {}
[INFO  - 2016-10-17T16:40:52.635Z] Session [77b65540-9488-11e6-8b50-6587ab547a16] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":false,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyAutoconfigUrl":null,"autodetect":false,"socksUsername":null,"socksPassword":null,"httpProxy":"173.208.36.69:3128","proxyType":"MANUAL","noProxy":null,"ftpProxy":"173.208.36.69:3128","socksProxy":"173.208.36.69:3128","hCode":373097727,"class":"org.openqa.selenium.Proxy","sslProxy":"173.208.36.69:3128"}}
[INFO  - 2016-10-17T16:40:52.635Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 77b65540-9488-11e6-8b50-6587ab547a16
Oct 17, 2016 10:40:52 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[INFO  - 2016-10-17T16:42:52.352Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-17T16:42:52.526Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
10:43:23.626 [main] INFO  org.slf4j.Logger - https://sors.doc.state.ok.us/svor/f?p=119:1: Obtained
[INFO  - 2016-10-17T16:45:52.463Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-17T16:47:52.352Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-17T16:47:52.526Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
