### ISSUE TITLE
sendKeys introduce want

### ISSUE THREAD

**Issue by nekulin** [detro/ghostdriver#497]
Run
```
$el =  $driver->findElement(WebDriverBy::cssSelector('input#name'));
$el->click()->sendKeys('My name');
```
Result:
mena yM

This can be entered in the wrong order, is it async ?

**Comment by jesg** [comment]
@nekulin it should be

```
$el->click();
$el->sendKeys('My name');
```

i would not expect `click` to return a value.

> This can be entered in the wrong order, is it async ?

i don't know much about the php client to answer that.

**Comment by nekulin** [comment]
Yes, you can't do the click, no click works
