### ISSUE TITLE
executePhantomJS documentation for accessing the current page not clear

### ISSUE THREAD

**Issue by justintaft** [detro/ghostdriver#512]
The PhantomJSDriver allows arbitrary scripts to be executed via  'executePhantomJS'. The currently selected page is accessible by `this`.

The documentation is unclear, and alludes  a variable named`page` as being the variable holding a reference to the page. This variable does not exist.

>      * A 'page' variable pointing to currently selected page is available for use.
>      * If there is no page yet, one is created.
https://github.com/detro/ghostdriver/blob/873c9d660a80a3faa743e4f352571ce4559fe691/binding/java/src/main/java/org/openqa/selenium/phantomjs/PhantomJSDriver.java#L149

**Comment by jesg** [comment]
you are correct.  the javadocs should be updated.

**Comment by jesg** [comment]
@justintaft can you create a pull request that improves the wording?
