### ISSUE TITLE
was phantomjsdriver 2.0 released?

### ISSUE THREAD

**Issue by anilreddy** [detro/ghostdriver#518]
@jesg have you released phantomjsdriver 2.0 while am trying to update the driver am getting the following error:

```java
<dependency>
	<groupId>com.github.detro</groupId>
	<artifactId>phantomjsdriver</artifactId>
	<version>2.0.0</version>
</dependency>
```
The POM for com.github.detro:phantomjsdriver:jar:2.0.0 is missing, no dependency information available

**Comment by jesg** [comment]
@anilreddy i pushed the 2.0.0 tag so it should work now.  you can see the build log [here](https://jitpack.io/com/github/detro/ghostdriver/2.0.0/build.log)

the project publishes the java client driver on jitpack.io now so you need to add jitpack.io as a repository in your maven project.

```xml
<repositories>
  <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
  </repository>
</repositories>
```

then add the following as a dependency.  the `artifactId` changed per the naming convention on jitpack.io.
```xml
<dependency>
    <groupId>com.github.detro</groupId>
    <artifactId>ghostdriver</artifactId>
    <version>2.0.0</version>
</dependency>
```

**Comment by ackmanx** [comment]
I get a 401 unauthorized when trying to fetch from jitpack.io. It prompts for a username/password and says "No read access to repo". Is this a private maven source?

**Comment by jesg** [comment]
@ackmanx 
>  Is this a private maven source?

it is public.  are you running java 8?

according to the [faq](https://jitpack.io/docs/FAQ/) page we should upgrade to gradle 2.11.

**Comment by ackmanx** [comment]
I think I had the artifactId wrong in Gradle. I found the link I used yesterday (https://jitpack.io/com/github/detro/phantomjsdriver/2.0.0/phantomjsdriver-2.0.0.pom) when I was trying it out.

The readme says to use `testCompile "com.github.detro.ghostdriver:phantomjsdriver:2.0.0"` but I get a 404 when I try that.

I changed the Gradle line to `compile 'com.github.detro:ghostdriver:2.0.0'` today and it updated without errors. Are these two the same or different?

**Comment by jesg** [comment]
> Are these two the same or different?

it should be `compile 'com.github.detro:ghostdriver:2.0.0'`.

@ackmanx you are correct.  i made a mistake when i updated the README.md.  it should be fixed in #519.

**Comment by anilreddy** [comment]
@jesg we are using our own repo and it is not allowing me to use other repos could you please release that jar in maven repo also so that we can use it.

**Comment by jesg** [comment]
@anilreddy i can release it to maven central.  i don't think detro is interested in publishing to maven central so i'll publish it to `com.github.jesg:ghostdriver:2.0.0`.

**Comment by jesg** [comment]
@anilreddy i've published the java client to maven central.

```xml
<dependency>
    <groupId>com.github.jesg</groupId>
    <artifactId>phantomjsdriver</artifactId>
    <version>2.0.0</version>
</dependency>
```

**Comment by anilreddy** [comment]
@jesg Cool.. Thank you..!!
