### ISSUE TITLE
Does docker-phantomjs support pop ups?

### ISSUE THREAD

**Issue by scythargon** [detro/ghostdriver#525]
Hello!

I'm not sure if it is the best place to ask this question (please kindly show me a better one if there is), but I assume that there I have more chances to get it answered:)

I'm using this repo -  https://hub.docker.com/r/wernight/phantomjs/ to load some page via selenium webdriver in python, then this page opens (or tries at least) one more window using javascript's `window.open` but I could not figure out how to access it and might be it is not even opened because there is only one item in `driver.window_handles` list.

The most sad thing is that I could not figure out on which layer there is a problem or misconfiguration exactly - PhantomJS, Ghostdriver, Selenium or Docker image.

Thank you for any feedback!

**Comment by jesg** [comment]
@scythargon please read the documentation [here](http://docs.seleniumhq.org/docs/03_webdriver.jsp#moving-between-windows-and-frames).  if you have a popup then there should be more than one element in `driver.window_handles`.

can you create a minimal example that reproduces the issue you are seeing?

**Comment by scythargon** [comment]
@jesg oh, I've figured it out, was my mistake, sorry and thank you!:)
