### ISSUE TITLE
Update Selenium WebDriver Atoms

### ISSUE THREAD

**Issue by cgatesman** [detro/ghostdriver#534]
Still using some old Selenium 2.39.0 WebDriver Atoms -- e.g. `is_displayed.js`

**Comment by cgatesman** [comment]
I believe this may help solve this issue:

https://github.com/ariya/phantomjs/issues/14128
https://github.com/SeleniumHQ/selenium/issues/1860

**Comment by jesg** [comment]
@cgatesman have you tried ghostdriver 2.0.0?

**Comment by jesg** [comment]
i'm unable to reproduce the issue on linux, phantomjs 2.1.1, and ghostdriver 2.0.0.  please upgrade the version of ghostdriver you are running.

**Comment by cgatesman** [comment]
How do you run phantomjs with a different version of ghostdriver?  I thought it is built into phantomjs.

**Comment by jesg** [comment]
> How do you run phantomjs with a different version of ghostdriver?

ghostdriver has an npm [package](https://www.npmjs.com/package/ghostdriver) that includes the up to date version of ghostdriver.  or you can look at the bash [script](https://github.com/detro/ghostdriver/blob/master/bin/ghostdriver.sh).

phantomjs does not have an active maintainer so it is unlikely there will be another phantomjs release with up to date ghostdriver any time soon.

**Comment by cgatesman** [comment]
I'm using Selenium Java, so I'm not starting phantomjs from the command line, so I have to see if this is possible.  What is `PHANTOMJS_GHOSTDRIVER_PATH` supposed to be set to?  Looking at the script, it looks like the way you tell phantomjs you're using a different ghostdriver is to basically pass `$PHANTOMJS_GHOSTDRIVER_PATH` as an argument to it?  Is that right, or am I missing something?

**Comment by cgatesman** [comment]
Ah...looks like maybe I can just set a `phantomjs.ghostdriver.path` in capabilities?

**Comment by jesg** [comment]
>  What is `PHANTOMJS_GHOSTDRIVER_PATH` supposed to be set to?

it is an environment variable that should be set to `src/main.js` in the ghostdriver project.

```
export PHANTOMJS_GHOSTDRIVER_PATH=<absolute path to src/main.js>
```

> I can just set a `phantomjs.ghostdriver.path` in capabilities?

yes

```java
sCaps.setCapability(PhantomJSDriverService.PHANTOMJS_GHOSTDRIVER_PATH_PROPERTY, <absolute path to src/main.js>);
```

**Comment by cgatesman** [comment]
Thanks for your help, @jesg!  I'll give this a whirl and report back. 👍

**Comment by cgatesman** [comment]
This worked out great, @jesg!  Thanks for the guidance!  And this does, indeed, fix the issue I have linked.  I'll update those issues.

**Comment by Aur3l14no** [comment]
@jesg That capabilities setting does not work with Python?
