### ISSUE TITLE
Support for ES6

### ISSUE THREAD

**Issue by skrajath** [detro/ghostdriver#541]
Hi I am currently using 1.4.3 version, but it has no support for ES6, like Map is recognised. When would this be supported and until then is there an alternative?

**Comment by jesg** [comment]
> When would this be supported

unlikely this will be supported now that phantomjs does not have a maintainer.

> is there an alternative

try firefox or chrome

**Comment by skrajath** [comment]
Thank you. I was looking for Headless, can there be Firefox and Chrome headless?

**Comment by jesg** [comment]
> I was looking for Headless, can there be Firefox and Chrome headless?

both firefox and chrome have a headless mode.  at the moment neither have full support for selenium.

**Comment by skrajath** [comment]
Thank you!!
