### ISSUE TITLE
Allow setting of custom logfile location when using the default configuration

### ISSUE THREAD

**Issue by markkrijgsman** [detro/ghostdriver#544]
I would like to use the method `PhantomJSDriverService.createDefaultService(Capabilities desiredCapabilities)` and still keep the possibility to set my own logfile location. I could use PhantomJSDriverService.Builder to set the logfile location, but this means I have to duplicate the setup done in `PhantomJSDriverService.createDefaultService(Capabilities desiredCapabilities)`. I tried creating a new branch in the repository in order to create a pull request, but it seems that I have no rights to do so. The code change is quite small:
```
public static final String PHANTOMJS_LOGFILE_PATH_PROPERTY = "phantomjs.logfile.path";

private static File findLogFile(Capabilities desiredCapabilities) {
    String logfilepath;
    if (desiredCapabilities != null &&
            desiredCapabilities.getCapability(PHANTOMJS_LOGFILE_PATH_PROPERTY) != null) {
        logfilepath = (String) desiredCapabilities.getCapability(PHANTOMJS_LOGFILE_PATH_PROPERTY);
    } else {
        logfilepath = PHANTOMJS_DEFAULT_LOGFILE;
    }
    return new File(logfilepath);
}
```
We can then call this method by [replacing the following line](https://github.com/detro/ghostdriver/blob/master/binding/java/src/main/java/org/openqa/selenium/phantomjs/PhantomJSDriverService.java#L200):
`.withLogFile(new File(PHANTOMJS_DEFAULT_LOGFILE))`
With:
`.withLogFile(findLogFile(desiredCapabilities))`

**Comment by jesg** [comment]
@markkrijgsman i'd rather not add more one off customizations around desired capabilities for the java client.

can you give an example of the issue you where having so i can reproduce it?

**Comment by markkrijgsman** [comment]
Hi, thanks for your reply. I would like to set a custom log file location while still using `PhantomJSDriverService.createDefaultService(Capabilities desiredCapabilities)`. Without my proposed change, I believe I'd have to do something like this (note that I'm forced to duplicate almost all of the `createDefaultService` method):
```
DesiredCapabilities capabilities = DesiredCapabilities.phantomjs();
new PhantomJSDriver(createService(capabilities), capabilities);

private PhantomJSDriverService createService(Capabilities desiredCapabilities) {
        Proxy proxy = null;
        if (desiredCapabilities != null) {
            proxy = Proxy.extractFrom(desiredCapabilities);
        }

        // Find PhantomJS executable
        File phantomjsfile = findPhantomJS(desiredCapabilities, PHANTOMJS_DOC_LINK, PHANTOMJS_DOWNLOAD_LINK);

        // Find GhostDriver main JavaScript file
        File ghostDriverfile = findGhostDriver(desiredCapabilities, GHOSTDRIVER_DOC_LINK, GHOSTDRIVER_DOWNLOAD_LINK);

        // Build & return service
        return new Builder().usingPhantomJSExecutable(phantomjsfile)
                .usingGhostDriver(ghostDriverfile)
                .usingAnyFreePort()
                .withProxy(proxy)
                // Note setting location of logfile to custom path
                .withLogFile("custom/path/to/logfile"))
                .withAcceptSslCerts(findAcceptSslCerts(desiredCapabilities))
                .usingCommandLineArguments(
                        findCLIArgumentsFromCaps(desiredCapabilities, PHANTOMJS_CLI_ARGS))
                .usingGhostDriverCommandLineArguments(
                        findCLIArgumentsFromCaps(desiredCapabilities, PHANTOMJS_GHOSTDRIVER_CLI_ARGS))
                .build();
}
```

With my proposed change, I am able to do the following:
```
DesiredCapabilities capabilities = DesiredCapabilities.phantomjs();
capabilities.setCapability(PhantomJSDriverService. PHANTOMJS_LOGFILE_PATH_PROPERTY, "custom/path/to/logfile");
new PhantomJSDriver(PhantomJSDriverService.createDefaultService(capabilities), capabilities);
```

**Comment by jesg** [comment]
@markkrijgsman 

i've reviewed the firefox [builder](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/GeckoDriverService.java#L143) and the chrome [builder](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/GeckoDriverService.java#L143).  in both of them you can set the log file path with a java system property.

i will accept a merge request that follows the same pattern.  i will also accept sane defaults in the service builder.  i will not accept the PHANTOMJS_LOGFILE_PATH_PROPERTY capability.

**Comment by bosofelipe** [comment]
@jesg Can you give me an example for configurate a custom path to log file?

I try this

capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS,
				new String[] { "--web-security=no", "--ignore-ssl-errors=yes","--webdriver-logfile="usr/local/logs/phantomjsdriver.log"
		});

But doesn´t work fine...

**Comment by markkrijgsman** [comment]
@jesg pull request has been created.

**Comment by jesg** [comment]
thanks @markkrijgsman
