### ISSUE TITLE
Can not connect to the Service phantomjs

### ISSUE THREAD

**Issue by leinue** [detro/ghostdriver#551]
## Meta -
OS:  
Ubuntu 5.4.0-6ubuntu1~16.04.4
64bit
Selenium Version:  
3.5
Browser:  
phantomjs

i use python
![image](https://user-images.githubusercontent.com/2469688/30054739-a43575d0-925f-11e7-8e35-fa35d9ab9477.png)

it works fine at local machine,when I uploaded the code to the server,it works failed.

> Can not connect to the Service phantomjs

but the command line phantomjs works correctly

![image](https://user-images.githubusercontent.com/2469688/30054380-801c1f60-925e-11e7-82d8-7938ffed8542.png)

how can i fix it??

**Comment by jesg** [comment]
this issue should be fixed in ghostdriver 2.0.  ghostdriver is packaged in an [npm package](https://www.npmjs.com/package/ghostdriver).

**Comment by jesg** [comment]
you can build phantomjs from source.  use my ]branch](https://github.com/jesg/phantomjs/tree/backport-ghostdriver-2-0-to-phantomjs-2-1) that backports ghostdriver 2.0.0 to phantomjs 2.1.1.  the build instructions can be found [here](https://github.com/jesg/phantomjs/tree/backport-ghostdriver-2-0-to-phantomjs-2-1/deploy)

ghostdriver is available on [npm](https://www.npmjs.com/package/ghostdriver).  you will need to set the `PHANTOMJS_BINARY_PATH` environment variable to the 2.5 beta binary.

if you do not like npm then you can clone the ghostdriver repository and run the [bash script](https://github.com/detro/ghostdriver/blob/master/bin/ghostdriver.sh).  you will need to set `PHANTOMJS_GHOSTDRIVER_PATH` to `src/main.js` and `PHANTOMJS_PATH` to the phantomjs binary.  (looks like the environment variable names are  inconsistent... that needs to be fixed).
