### ISSUE TITLE
Can't register ghostdriver/webdriver with Selenium Grid

### ISSUE THREAD

**Issue by lawred2** [detro/ghostdriver#553]
With version 2.1.1

```
[INFO  - 2017-05-09T20:56:41.952Z] GhostDriver - Main - running on port 8080
[INFO  - 2017-05-09T20:56:41.960Z] GhostDriver - Main - registering to Selenium HUB 'http://127.0.0.1:4445' version:  using '127.0.0.1:8080' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2017-05-09T20:56:41.992Z] GhostDriver - main.fail - {"line":97,"sourceURL":"phantomjs://platform/hub_register.js","stack":"register@phantomjs://platform/hub_register.js:97:79\nglobalcode@phantomjs://code/main.js:78:37"}

  phantomjs://platform/console++.js:263 in error
```

This is with both linux and Mac OSX.

I can't see anything in the selenium grid logs to indicate that there was even a request from Ghostdriver to register a node.

Is anyone using Phantomjs as a node in selenium Grid? When I start PhantomJs without the --webdrvier-selenium-grid-hub command line parameter - the webdriver starts fine. Just not when I want it to register with Selenium.

**Comment by jesg** [comment]
this issue is fixed in ghostdriver 2.0. ghostdriver 2.0 is packaged in an npm package.

**Comment by lawred2** [comment]
How can I go about bundling that with PhantomJS?

**Comment by jesg** [comment]
you can build phantomjs from source but imo it is a pia.  it can easily suck up 2-3 days to figure out how to do it correctly.  the binaries for 2.5 are [here](https://bitbucket.org/ariya/phantomjs/downloads/).  2.5 beta is not built with ghostdriver 2.0.0.  you will need to install some shared libraries.

ghostdriver is available on [npm](https://www.npmjs.com/package/ghostdriver).  you will need to set the `PHANTOMJS_BINARY_PATH` environment variable to the 2.5 beta binary.

if you do not like npm then you can clone the ghostdriver repository and run the [bash script](https://github.com/detro/ghostdriver/blob/master/bin/ghostdriver.sh).  you will need to set `PHANTOMJS_GHOSTDRIVER_PATH` to `src/main.js` and `PHANTOMJS_PATH` to the phantomjs binary.  (looks like the environment variable names are  inconsistent... that needs to be fixed).
