### ISSUE TITLE
How to obtain DEBUG level logs via Webdriver logging API?

### ISSUE THREAD

**Issue by MarkusPint** [detro/ghostdriver#554]
Hi,
Here's my NodeJS code without the clutter:

```
var capabilities = Capabilities.phantomjs();

capabilities.set("phantomjs.cli.args", [
 '--webdriver-logfile=ghostlog',
 '--webdriver-loglevel=DEBUG',
 '--debug=true'
]);

var prefs = new logging.Preferences();
prefs.setLevel('har', logging.Level.DEBUG);

capabilities.setLoggingPrefs(prefs)

driver = new webdriver.Builder()
.withCapabilities(capabilities)
.build();

driver.get('http://cnn.com').then(() => {
  driver.manage().logs().get('har').then((logs) => {
    console.log(logs);
  });
});
```

DEBUG-level logs are only visible in the file "ghostlog", but in console, after obtaining the HAR-type logs via Webdriver logging API, it only shows INFO-level logs. How can I obtain DEBUG-level logs via Webdriver logging API?

PhantomJS version 2.1.1

**Comment by jesg** [comment]
> How can I obtain DEBUG-level logs via Webdriver logging API?

ghostdriver only supports browser logs and har logs.
