### ISSUE TITLE
How can I specify ghostdriver location when using Python + Selenium + PhantomJS?

### ISSUE THREAD

**Issue by Aur3l14no** [detro/ghostdriver#555]
The latest version of PhantomJS still uses ghostdriver 1.2 which causes exceptions when I change the userAgent.

`dcap = DesiredCapabilities.PHANTOMJS.copy()`
`dcap['phantomjs.ghostdriver.path'] = '.../main.js'`  
`driver = webdriver.PhantomJS(desired_capabilities=dcap)`

The above doesn't seem to work.

**Comment by jesg** [comment]
@Aur3l14no it should be

```
dcap['phantomjs.ghostdriver.path'] = '<absolute path>/main.js'
```

**Comment by Aur3l14no** [comment]
Yes that's what I did. And according to ghostdriver's log file, that setting didn't apply.

And sorry for my late reply. I'm still getting used to open source things.

**Comment by jesg** [comment]
@Aur3l14no my mistake.  i forgot that setting that only applies to the java client.

if you are on *nix you can use this bash [script](https://github.com/detro/ghostdriver/blob/master/bin/ghostdriver.sh).  set the `PHANTOMJS_GHOSTDRIVER_PATH` environment variable to main.js.

```
driver = webdriver.PhantomJS(executable_path='<absolute path>/ghostdriver.sh', desired_capabilities=dcap)
```

or you can install the npm [package](https://www.npmjs.com/package/ghostdriver).

```
driver = webdriver.PhantomJS(executable_path='<absolute path>/ghostdriver', desired_capabilities=dcap)
```

**Comment by Aur3l14no** [comment]
Ah thanks. It's working now.
